// Generated by CoffeeScript 1.3.3
(function() {
  var Entry, EntryList, EntryListView, EntryView, PathView, Repository, SyncClient, async, commitModels, difference, init, omit, pluck, queryName, renderView, resetCollection, values, _ref, _ref1;

  window.jQuery = window.$ = require('jquery-browserify');

  window.Backbone = require('backbone');

  async = require('async');

  Backbone.setDomLibrary($);

  _ref = window._ = require('underscore'), omit = _ref.omit, difference = _ref.difference, values = _ref.values, pluck = _ref.pluck;

  Repository = require('synclib').Repository;

  _ref1 = require('./views'), PathView = _ref1.PathView, EntryView = _ref1.EntryView, EntryListView = _ref1.EntryListView;

  Entry = Backbone.Model.extend({
    idAttribute: 'path'
  });

  EntryList = Backbone.Collection.extend({
    model: Entry
  });

  renderView = function(view, selector) {
    return $(selector).html(view.render().el);
  };

  resetCollection = function(collection, branch) {
    var data, models;
    data = branch.allPaths();
    models = data.map(function(_arg) {
      var entry, path, value;
      path = _arg.path, value = _arg.value;
      entry = new Entry(JSON.parse(value));
      entry.set(entry.idAttribute, path);
      return entry;
    });
    return collection.reset(models);
  };

  commitModels = function(models, branch) {
    var data, model, _i, _len;
    data = {};
    for (_i = 0, _len = models.length; _i < _len; _i++) {
      model = models[_i];
      data[model.id] = JSON.stringify(omit(model.toJSON(), model.idAttribute));
    }
    return branch.commit(data);
  };

  SyncClient = (function() {

    function SyncClient(_arg) {
      var _ref2;
      _ref2 = _arg != null ? _arg : {}, this.branch = _ref2.branch, this.name = _ref2.name;
      this.remotes = {};
    }

    SyncClient.prototype.fetch = function(cb) {
      var obj;
      obj = this;
      return $.get('/head', function(_arg) {
        var from, heads, to;
        heads = _arg.heads;
        from = JSON.stringify(values(obj.remotes));
        to = JSON.stringify(pluck(heads, 'head'));
        return $.get('/delta?from=' + from + '&to=' + to, function(res) {
          var head, name, _i, _len, _ref2;
          console.log('delta received', res);
          obj.branch.repo.treeStore.writeAll(res.trees);
          for (_i = 0, _len = heads.length; _i < _len; _i++) {
            _ref2 = heads[_i], name = _ref2.name, head = _ref2.head;
            obj.branch.merge({
              ref: head
            });
            obj.remotes[name] = head;
          }
          return cb(null);
        });
      });
    };

    SyncClient.prototype.push = function() {
      var delta, obj;
      obj = this;
      delta = this.branch.repo.deltaData(this.branch.deltaHashs({
        from: values(this.remotes)
      }));
      console.log('send delta', delta);
      return $.ajax({
        type: 'POST',
        url: '/delta',
        data: JSON.stringify({
          trees: delta.trees
        }),
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: function() {
          obj.remotes[obj.name] = obj.branch.head;
          return $.ajax({
            type: 'PUT',
            url: '/head/' + obj.name,
            data: {
              hash: obj.branch.head
            }
          });
        }
      });
    };

    return SyncClient;

  })();

  init = function(name) {
    var branch, changed, changedEntries, entries, entryListView, repo, syncClient, trackChanges;
    repo = new Repository;
    branch = repo.branch();
    syncClient = new SyncClient({
      branch: branch,
      name: name
    });
    entries = new EntryList;
    changedEntries = new Backbone.Collection;
    changed = function(model) {
      return changedEntries.add(model);
    };
    trackChanges = function(model) {
      return model.on('change', function() {
        return changed(model);
      });
    };
    entries.on('reset', function() {
      var each, _i, _len, _ref2, _results;
      _ref2 = entries.models;
      _results = [];
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        each = _ref2[_i];
        _results.push(trackChanges(each));
      }
      return _results;
    });
    entries.on('add', function(model) {
      trackChanges(model);
      return changed(model);
    });
    entryListView = new EntryListView({
      collection: entries
    });
    entryListView.on('selected', function(entry) {
      var entryView;
      entryView = new EntryView({
        model: entry
      });
      entryView.on('save', function(newEntry) {
        return entry.set(newEntry);
      });
      return renderView(entryView, '#detail');
    });
    $('#btn-add').click(function() {
      var entryView;
      entryView = new EntryView();
      entryView.on('save', function(newEntry) {
        return entries.add(newEntry);
      });
      return renderView(entryView, '#detail');
    });
    $('#btn-commit').click(function() {
      commitModels(changedEntries.models, branch);
      return changedEntries.reset();
    });
    $('#btn-push').click(function() {
      return syncClient.push();
    });
    $('#btn-fetch').click(function() {
      return syncClient.fetch(function() {
        return resetCollection(entries, branch);
      });
    });
    return renderView(entryListView, '#entries');
  };

  queryName = function(cb) {
    $('#setup-modal').modal({
      backdrop: 'static',
      keyboard: false
    });
    return $('#setup-modal .submit').click(function() {
      $('#setup-modal').modal('hide');
      return cb(null, $('#setup-client').val());
    });
  };

  $(function() {
    return queryName(function(err, name) {
      $('#client-name').text(name);
      return init(name);
    });
  });

}).call(this);
