// Generated by CoffeeScript 1.3.3
(function() {
  var get, post, put;

  post = function(url, data, cb) {
    return $.ajax({
      type: 'POST',
      url: url,
      data: JSON.stringify(data),
      contentType: "application/json; charset=utf-8",
      dataType: "json",
      success: function(res) {
        return cb(null, res);
      }
    });
  };

  put = function(url, data, cb) {
    return $.ajax({
      type: 'PUT',
      url: url,
      data: JSON.stringify(data),
      contentType: "application/json; charset=utf-8",
      dataType: "json",
      success: function(res) {
        return cb(null, res);
      }
    });
  };

  get = function(url, cb) {
    return $.get(url, function(res) {
      return cb(null, res);
    });
  };

  module.exports = {
    post: post,
    put: put,
    get: get
  };

}).call(this);
